# Generated by Django 3.2.5 on 2021-09-17 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deskription',
            new_name='description',
        ),
    ]
