# Generated by Django 3.2.5 on 2021-09-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_deskription_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POST',
        ),
    ]
