# Generated by Django 3.2.5 on 2021-09-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='deskripsi',
        ),
    ]
