# Generated by Django 3.2.5 on 2021-09-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='published',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='category',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='body',
            new_name='pesan',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='updated',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
