# Generated by Django 3.2.5 on 2021-09-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bukutamu',
            old_name='date',
            new_name='waktu',
        ),
        migrations.AddField(
            model_name='bukutamu',
            name='akun',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='pesan',
            field=models.TextField(max_length=500),
        ),
    ]
