# Generated by Django 3.2.5 on 2021-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coba', '0002_auto_20210928_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bukutamu',
            name='akun',
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='pesan',
            field=models.CharField(max_length=500),
        ),
    ]
